os:
  - linux
#  - osx

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libgtest-dev
    - liblua5.2-dev
    - zlib1g-dev
    - g++-5
    - gcc-5
    - clang
    - libc6:i386
    - lua5.1
    - libdbus-1-dev
    - build-essential
    - mercurial
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - libasound2-dev
    - libpulse-dev
    - libaudio-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxxf86vm-dev
    - libxss-dev
    - libgl1-mesa-dev
    - libesd0-dev
    - libdbus-1-dev
    - libudev-dev
    - libgles1-mesa-dev
    - libgles2-mesa-dev
    - libegl1-mesa-dev
    - libibus-1.0-dev
    - libsdl1.2-dev
    - libsdl-ttf2.0-dev
    - libvorbis-dev
    - zlib1g-dev
    - gettext
    - libtheora-dev
    - libjpeg-dev
    - libpng12-dev
    - libcurl4-openssl-dev
    - libsdl-mixer1.2-dev
    - libxml2-dev
    - libopenal-dev
    - p7zip-full
    - binutils-dev
    - libxvidcore-dev
    - libmxml-dev
    - libiberty-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    sources:
    - ubuntu-toolchain-r-test
    - zoogie-sdl2-snapshots

# currently disabled, because sdl2 ppa is not yet available
#    - libsdl2-dev
#    - libsdl2-net-dev
#    - libsdl2-image-dev
#    - libsdl2-mixer-dev

before_install:
# We need a more up to date version of cmake to use macros like "target_compile_definitions"
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade cmake
# Following packages are not available and need to be downloaded here
  - sudo apt-get install libgtkglext1-dev libgtksourceview2.0-dev

script:
# On Linux, we turn on all the projects
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DUFOAI_BUILD_GAME=ON -DUFOAI_BUILD_UFO2MAP=ON -DUFOAI_BUILD_UFODED=ON -DUFOAI_BUILD_UFO=ON -DUFOAI_BUILD_UFOMODEL=ON -DUFOAI_BUILD_UFOSLICER=ON -DUFOAI_BUILD_UFORADIANT=ON -DUFOAI_BUILD_UFOTESTALL=ON && make; fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -G Xcode && xcodebuild -list -project ufoai.xcodeproj && xcodebuild -project ufoai.xcodeproj -target ALL_BUILD | xcpretty -f `xcpretty-travis-formatter`; fi

#notifications:
#  email:

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

cache: apt
